# Generated by Django 3.1.7 on 2021-04-03 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expense',
            old_name='created_at',
            new_name='date',
        ),
        migrations.RemoveField(
            model_name='expense',
            name='updated',
        ),
    ]
