# Generated by Django 3.1.7 on 2022-02-16 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_auto_20210628_0005'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='auth_providers',
            field=models.CharField(default=None, max_length=255),
        ),
    ]
