# Generated by Django 3.1.7 on 2022-02-16 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_auto_20220216_1556'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='auth_providers',
        ),
    ]
