# Generated by Django 3.1.7 on 2022-02-16 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0009_remove_user_auth_providers'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='auth_providers',
            field=models.CharField(default=None, max_length=255),
        ),
    ]
